import Head from 'next/head'
import { ExpandableCard, useExpandableCard } from '../components/ExpandableCard'
import { Layout } from '../components/Layout'

export default function Home() {
  const expandableCardProps = useExpandableCard()

  return (
    <>
      <Head>
        <title>CoinGecko coins</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout title="Coin">
        <ExpandableCard title="Something" {...expandableCardProps}>
          CoinGecko Coins
        </ExpandableCard>
        <footer>Jon Walz</footer>
      </Layout>
    </>
  )
}
