import Head from 'next/head'
import { Layout } from '../components/Layout'
import { Tokens } from '../components/Tokens'

export default function Home() {
  return (
    <>
      <Head>
        <title>CoinGecko coins</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout title="Coin-go Boingo">
        <Tokens />
        <footer>Jon Walz 2022</footer>
      </Layout>
    </>
  )
}
