import Head from 'next/head'
import Image from 'next/image'
import { ExpandableCard, useExpandableCard } from '../components/Card'
import styles from '../styles/Home.module.css'

export default function Home() {
  const expandableCardProps = useExpandableCard()
  return (
    <div className={styles.container}>
      <Head>
        <title>CoinGecko coins</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ExpandableCard title="Something" {...expandableCardProps}>
        CoinGecko Coins
      </ExpandableCard>
      <footer className={styles.footer}>Jon Walz</footer>
    </div>
  )
}
